; LeafLink — ESP32-S3 Master Node
; PlatformIO project configuration

[env:esp32-s3-devkitc-1]
platform  = espressif32
board     = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200
upload_speed  = 921600

lib_deps =
    me-no-dev/AsyncTCP @ ^1.1.1
    me-no-dev/ESPAsyncWebServer @ ^1.2.3
    bblanchon/ArduinoJson @ ^6.21.5

; More flash for the app (SPA is embedded in PROGMEM)
board_build.partitions = huge_app.csv

build_flags =
    -DCORE_DEBUG_LEVEL=3
    -std=gnu++17

build_unflags =
    -std=gnu++11